inputNumberOne, inputNumberTwo = map(int, input().split())
print(inputNumberOne + inputNumberTwo)
print(inputNumberOne - inputNumberTwo)
print(inputNumberOne * inputNumberTwo)
print(inputNumberOne // inputNumberTwo)
print(inputNumberOne % inputNumberTwo)